
services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: 
      - .env  # Charger les variables d'environnement depuis le fichier .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file: 
      - .env  # Charger les variables d'environnement depuis le fichier .env
    environment:
      - FASTAPI_URL=http://api:8000  # Variable spécifique au frontend
    depends_on:
      - api